[book]
authors = []
language = "zh"
src = "src"
title = "OnlyFans 博主介绍"

[output.html]
default-theme = "ayu"
git-repository-url = "https://github.com/javwiki/onlyfans"
edit-url-template = "https://github.com/javwiki/onlyfans/edit/main/{path}"
preferred-dark-theme = "navy"
